class AppConstant {
  static List<Map<String, dynamic>> list = [
    {
      "sl_no": 1,
      "district": "Ariyalur",
      "teshil_taluk": "Ariyalur",
      "area": "Ariyalur",
      "center_type": "Permanent",
      "center_name": "Collector Office",
      "center_address": "Collector Office Ariyalur",
      "contact_no": 8508653194,
      "pincode": 621704,
      "post_office": "Ariyalur",
      "latitude": "11° 12.65' N",
      "longitude": "79° 21.75' E",
      "altitude": "80.70m"
    },
    {
      "sl_no": 2,
      "district": "Ariyalur",
      "teshil_taluk": "Ariyalur(M)",
      "area": "Ariyalur",
      "center_type": "Permanent",
      "center_name": "Ariyalur Municipality",
      "center_address": "Ariyalur Municipality",
      "contact_no": 9865014799,
      "pincode": 621704,
      "post_office": "Ariyalur",
      "latitude": "11° 8.30' N",
      "longitude": "79° 4.50' E",
      "altitude": "246.80m"
    },
    {
      "sl_no": 3,
      "district": "Ariyalur",
      "teshil_taluk": "Jayankondam(M)",
      "area": "Udayarpalayam",
      "center_type": "Permanent",
      "center_name": "Jayankondam Municipality",
      "center_address": "Jayankondam Municipality",
      "contact_no": 9659935665,
      "pincode": 621802,
      "post_office": "Jayamkondacholapuram",
      "latitude": "11° 12.41' N",
      "longitude": "79° 4.60' E",
      "altitude": "212.00m"
    },
    {
      "sl_no": 4,
      "district": "Chennai",
      "teshil_taluk": "Chennai",
      "area": "Chennai",
      "center_type": "Permanent",
      "center_name": "Chennai Collector Office",
      "center_address": "Singaravelar Maligai,Rajaji Salai",
      "contact_no": 9940479376,
      "pincode": 600001,
      "post_office": "Chennai G.p",
      "latitude": "13° 5.77' N",
      "longitude": "80° 17.51' E",
      "altitude": "52.40m"
    },
    {
      "sl_no": 5,
      "district": "Chennai",
      "teshil_taluk": "Nandanam",
      "area": "Chennai",
      "center_type": "Camp-Mode",
      "center_name": "Elcot Office",
      "center_address": "Mhu Complex,Nandanam Chennai",
      "contact_no": 9750704494,
      "pincode": 600035,
      "post_office": "Nandanam",
      "latitude": "13° 3.39' N",
      "longitude": "80° 14.31' E",
      "altitude": "143.00m"
    },
    {
      "sl_no": 6,
      "district": "Chennai",
      "teshil_taluk": "Adayar",
      "area": "Chennai",
      "center_type": "Camp-Mode",
      "center_name": "Indusind Bank",
      "center_address": "Adayar",
      "contact_no": 9362601128,
      "pincode": 600020,
      "post_office": "Adayar",
      "latitude": "12° 57.94' N",
      "longitude": "80° 14.90' E",
      "altitude": "3032.50m"
    },
    {
      "sl_no": 7,
      "district": "Chennai",
      "teshil_taluk": "Royapettah",
      "area": "Chennai",
      "center_type": "Permanent",
      "center_name": "Indusind Bank",
      "center_address": "Royapettah",
      "contact_no": 9884350474,
      "pincode": 600014,
      "post_office": "Royapettah",
      "latitude": "13° 2.52' N",
      "longitude": "80° 16.05' E",
      "altitude": "48.50m"
    },
    {
      "sl_no": 8,
      "district": "Chennai",
      "teshil_taluk": "Velacherry",
      "area": "Chennai",
      "center_type": "Camp-Mode",
      "center_name": "Indusind Bank",
      "center_address": "Velachery 100ft Bypass Road Near Simran Appakadai",
      "contact_no": 8508476916,
      "pincode": 600042,
      "post_office": "Velacherry",
      "latitude": "12° 56.28' N",
      "longitude": "80° 15.02' E",
      "altitude": "16.50m"
    },
    {
      "sl_no": 9,
      "district": "Chennai",
      "teshil_taluk": "Madipakkam",
      "area": "Sholinganallur",
      "center_type": "Camp-Mode",
      "center_name": "Indusind Bank",
      "center_address": "23 Madavekkam Main Road Madipakkam",
      "contact_no": 9626086029,
      "pincode": 600091,
      "post_office": "Madipakkam",
      "latitude": "12° 57.83' N",
      "longitude": "80° 11.26' E",
      "altitude": "37.90m"
    },
    {
      "sl_no": 10,
      "district": "Chennai",
      "teshil_taluk": "Mogappair",
      "area": "Ambattur",
      "center_type": "Camp-Mode",
      "center_name": "Indusind Bank",
      "center_address": "Thiruvalluvar Nagar",
      "contact_no": 9629468760,
      "pincode": 600037,
      "post_office": "Mogappair",
      "latitude": "13° 5.18' N",
      "longitude": "80° 10.75' E",
      "altitude": "-148.00m"
    },
    {
      "sl_no": 11,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Coimbatorecity Municiple Corporation",
      "center_address": "Townhall Main Zone",
      "contact_no": 9976273368,
      "pincode": 641001,
      "post_office": "Coimbatore",
      "latitude": "10° 59.61' N",
      "longitude": "76° 57.68' E",
      "altitude": "382.20m"
    },
    {
      "sl_no": 12,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Coimbatore Corporation",
      "center_address": "Coimbatore Corporation Office (East Zonal)",
      "contact_no": 9486300095,
      "pincode": 641005,
      "post_office": "Singanallur",
      "latitude": "11° .14' N",
      "longitude": "77° 1.77' E",
      "altitude": "119.70m"
    },
    {
      "sl_no": 13,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "RS Puram",
      "center_address": "West Zone Rspuram Coimbatore",
      "contact_no": 9942879685,
      "pincode": 641002,
      "post_office": "Rathinasabapathy Puram",
      "latitude": "11° .38' N",
      "longitude": "76° 57.17' E",
      "altitude": "431.20m"
    },
    {
      "sl_no": 14,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Corporation North Zone",
      "center_address": "Balasubramaniyam Road",
      "contact_no": 8807121558,
      "pincode": 641037,
      "post_office": "Pappanaickenpalayam",
      "latitude": "11° .97' N",
      "longitude": "76° 58.66' E",
      "altitude": "339.00m"
    },
    {
      "sl_no": 15,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Centralzone",
      "center_address": "Coimbatore Corparation",
      "contact_no": 9487691898,
      "pincode": 641018,
      "post_office": "Coimbatore Central",
      "latitude": "11° .19' N",
      "longitude": "76° 58.26' E",
      "altitude": "436.40m"
    },
    {
      "sl_no": 16,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Colletrate",
      "center_address": "Colletrate",
      "contact_no": 9843800611,
      "pincode": 641018,
      "post_office": "Coimbatore Central",
      "latitude": "11° .01' N",
      "longitude": "76° 58.06' E",
      "altitude": "436.00m"
    },
    {
      "sl_no": 17,
      "district": "Coimbatore",
      "teshil_taluk": "Coimbatore South",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Coimbatore Collectorate",
      "center_address": "Coimbatore Collectorate",
      "contact_no": 7708572200,
      "pincode": 641018,
      "post_office": "Coimbatore Central",
      "latitude": "11° .01' N",
      "longitude": "76° 58.04' E",
      "altitude": "425.40m"
    },
    {
      "sl_no": 18,
      "district": "Coimbatore",
      "teshil_taluk": "Goundampalayam",
      "area": "Coimbatore North",
      "center_type": "Permanent",
      "center_name": "Kavundapalayam",
      "center_address": "Kavundampalayam",
      "contact_no": 8122363751,
      "pincode": 641030,
      "post_office": "Kavundampalayam Colony",
      "latitude": "11° 2.72' N",
      "longitude": "76° 56.11' E",
      "altitude": "1595.80m"
    },
    {
      "sl_no": 19,
      "district": "Coimbatore",
      "teshil_taluk": "Kuniyamuthur",
      "area": "Coimbatore South",
      "center_type": "Permanent",
      "center_name": "Kuniyamuthur Zone",
      "center_address": "Coimbatore Corporation Kuniyamuthur",
      "contact_no": 9943716180,
      "pincode": 641008,
      "post_office": "Kuniyamuthur",
      "latitude": "10° 57.42' N",
      "longitude": "76° 57.74' E",
      "altitude": "256.30m"
    },
    {
      "sl_no": 20,
      "district": "Coimbatore",
      "teshil_taluk": "Mettupalayam",
      "area": "Mettupalayam",
      "center_type": "Permanent",
      "center_name": "Mettupalayam Zone",
      "center_address": "Mettupalayam Muncipality",
      "contact_no": 9500510180,
      "pincode": 641301,
      "post_office": "Mettupalayam",
      "latitude": "11° 17.56' N",
      "longitude": "76° 56.46' E",
      "altitude": "334.70m"
    },
    {
      "sl_no": 21,
      "district": "Coimbatore",
      "teshil_taluk": "Pollachi",
      "area": "Pollachi",
      "center_type": "Permanent",
      "center_name": "Pollachi",
      "center_address": "Pollachi Municipal Office",
      "contact_no": 8526225205,
      "pincode": 642001,
      "post_office": "Pollachi",
      "latitude": "10° 39.52' N",
      "longitude": "77° .52' E",
      "altitude": "300.10m"
    },
  ];
}
